application: mkdomeni
version: 1
runtime: python
api_version: 1

handlers:
- url: /images
  static_dir: images

- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /db
  static_dir: db
  login: admin

- url: /getdomains
  script: soberi_domejni.py
  login: admin

- url: .*
  script: main.py

